### PR TITLE
Replace placeholder logo with a complete one

### PR DESCRIPTION
**Pull request by ghost**
Addresses #1.

Finished roughing out a design in Inkscape. Ensured the stroke colours for paths were made white. I also added a drop shadow filter definition (should be supported by most modern browsers) within the logo SVG file itself to hopefully give it a bit more clarity when being displayed on the home page.

### CODE REVIEW

**Comment by nii236** [comment]
Some swan logos for ideas.

**Comment by ghost** [comment]
Duly noted. :+1:

They're very nice designs, but I'm going to stick with using rounded cap outlines for paths to stay consistent with the main NodeSchool logo style.

**Comment by ghost** [comment]
@nii236, I've updated the design. Let me know what you think.

**Comment by nii236** [comment]
For reference:



Can I see it without the buildings at all, and bigger swan?

I'll merge for now, since it beats having the empty logo

**Pull request merged**
